---
title: "Structured Topic Model"
authors: Abhas, Anna, Maria, Sofia
output: html_notebook
---


```{r}
library(stm)
library(tidyverse)
library(tidyr)
library(tidytext)

```


```{r}

common_terms = c("us", "said", "also", 
                 "one", "two", "three", "four", "five", "six", "seven", "eight", "nine",
                 "january", "february", "march", "april", "may", "june", "july", "august", 
                 "september", "october", "november", "december")

wiki_dfm_trim <- dfm_select(wiki_dfm, pattern = common_terms, selection = "remove", valuetype = "fixed")
wiki_dfm_trim <- dfm_trim(wiki_dfm, min_termfreq = 100, max_termfreq = 5000, min_docfreq = 10, max_docfreq = 500)

topfeatures(wiki_dfm_trim, 100)

converted_stm <- convert(wiki_dfm_trim, to = "stm", docvars = docvars(wiki_corpus))

processed <- textProcessor(wiki_files$text, metadata = wiki_files)
out <- prepDocuments(processed$documents, processed$vocab, processed$meta)
docs <- out$documents
vocab <- out$vocab
meta <-out$meta

for (i in 1:length(converted_stm$meta$Party)) {
  if(converted_stm$meta$Party[i] == "D"){
    out$meta$Party[i] = 1
  } else{
    out$meta$Party[i] = -1
  }
  
  if(is.na(converted_stm$meta$Gender[i])){
    out$meta$Gender[i] = "0"
  } else if(converted_stm$meta$Gender[i] == "female"){
    out$meta$Gender[i] = "1"
  } else{
    out$meta$Gender[i] = "-1"
  }
}

out$meta$Gender <- sapply(out$meta$Gender, as.numeric)
out$meta$Party <- sapply(out$meta$Party, as.numeric)

```


# Creating STM
```{r}

wiki_stm <- stm(converted_stm$documents, converted_stm$vocab, K=10, 
                prevalence=~converted_stm$meta$Party, 
                data=converted_stm$meta, max.em.its=100, init.type="Spectral")

labelTopics(wiki_stm)

plot(wiki_stm)

```


# Tidy STM
```{r}

td_beta <- tidy(wiki_stm)

td_beta %>%
    group_by(topic) %>%
    top_n(10, beta) %>%
    ungroup() %>%
    mutate(topic = paste0("Topic ", topic),
           term = reorder_within(term, beta, topic)) %>%
    ggplot(aes(term, beta, fill = as.factor(topic))) +
    geom_col(alpha = 0.8, show.legend = FALSE) +
    facet_wrap(~ topic, scales = "free_y") +
    coord_flip() +
    scale_x_reordered() +
    labs(x = NULL, y = expression(beta),
         title = "Highest word probabilities for each topic",
         subtitle = "Different words are associated with different topics")

```


#Exploring and Plotting Topics
```{r}

predict_topics <- estimateEffect(formula = 1:10 ~ Party + s(Gender), 
                                 stmobj = wiki_stm, 
                                 metadata = out$meta,
                                 uncertainty = "Global")

summary(predict_topics)

plot(predict_topics, "Party", topics = c(1,2,3,4,5,6,7,8,9,10),
     model = wiki_stm, method = "difference",
     cov.value1 = "Party", 
     cov.value2 = "Gender",
     xlab = "Republican ................................................ Democratic",
     main = "Republican vs. Democratic",
     xlim = c(-0.1, 0.1), labeltype = "custom",
     custom.labels = c('Topic 1','Topic 2','Topic 3', 'Topic 4', 'Topic 5',
                       'Topic 6', 'Topic 7', 'Topic 8', 'Topic 9', 'Topic 10'))


```




